#!/bin/bash
set -euo pipefail
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

apt-get update -y
apt-get install -y curl

curl -fsSL https://raw.githubusercontent.com/travisvill3-Aggie/ITSM-622-JSON-/refs/heads/main/MongoDB-M7%20Assignment
chmod +x /tmp/setup.sh
bash /tmp/setup.sh
